package com.opentext.livelink.service.workflowservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:15:49.929-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "WorkflowService", 
                  wsdlLocation = "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-workflow-service-ws/src/main/resources/WorkflowService.wsdl",
                  targetNamespace = "urn:WorkflowService.service.livelink.opentext.com") 
public class WorkflowService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:WorkflowService.service.livelink.opentext.com", "WorkflowService");
    public final static QName BasicHttpBindingWorkflowService = new QName("urn:WorkflowService.service.livelink.opentext.com", "BasicHttpBinding_WorkflowService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-workflow-service-ws/src/main/resources/WorkflowService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(WorkflowService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-workflow-service-ws/src/main/resources/WorkflowService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public WorkflowService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WorkflowService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WorkflowService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public WorkflowService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public WorkflowService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public WorkflowService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns WorkflowService
     */
    @WebEndpoint(name = "BasicHttpBinding_WorkflowService")
    public WorkflowService getBasicHttpBindingWorkflowService() {
        return super.getPort(BasicHttpBindingWorkflowService, WorkflowService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WorkflowService
     */
    @WebEndpoint(name = "BasicHttpBinding_WorkflowService")
    public WorkflowService getBasicHttpBindingWorkflowService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingWorkflowService, WorkflowService.class, features);
    }

}
