package com.opentext.livelink.service.workflowservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:15:49.894-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", name = "WorkflowService")
@XmlSeeAlso({ObjectFactory.class, com.opentext.livelink.service.core.ObjectFactory.class, com.opentext.livelink.service.docman.ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface WorkflowService {

    @WebMethod(operationName = "GetWorkItemData", action = "urn:WorkflowService.service.livelink.opentext.com/GetWorkItemData")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetWorkItemData", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetWorkItemDataResponse")
    @RequestWrapper(localName = "GetWorkItemData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetWorkItemData")
    @ResponseWrapper(localName = "GetWorkItemDataResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetWorkItemDataResponse")
    @WebResult(name = "GetWorkItemDataResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.workflowservice.ApplicationData> getWorkItemData(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID
    );

    @WebMethod(operationName = "UpdateProcessData", action = "urn:WorkflowService.service.livelink.opentext.com/UpdateProcessData")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/UpdateProcessData", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/UpdateProcessDataResponse")
    @RequestWrapper(localName = "UpdateProcessData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.UpdateProcessData")
    @ResponseWrapper(localName = "UpdateProcessDataResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.UpdateProcessDataResponse")
    public void updateProcessData(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "applicationData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.util.List<com.opentext.livelink.service.workflowservice.ApplicationData> applicationData
    );

    @WebMethod(operationName = "GetProcessDefinition", action = "urn:WorkflowService.service.livelink.opentext.com/GetProcessDefinition")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetProcessDefinition", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetProcessDefinitionResponse")
    @RequestWrapper(localName = "GetProcessDefinition", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessDefinition")
    @ResponseWrapper(localName = "GetProcessDefinitionResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessDefinitionResponse")
    @WebResult(name = "GetProcessDefinitionResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessDefinition getProcessDefinition(
        @WebParam(name = "objectID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long objectID
    );

    @WebMethod(operationName = "SuspendProcess", action = "urn:WorkflowService.service.livelink.opentext.com/SuspendProcess")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/SuspendProcess", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/SuspendProcessResponse")
    @RequestWrapper(localName = "SuspendProcess", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SuspendProcess")
    @ResponseWrapper(localName = "SuspendProcessResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SuspendProcessResponse")
    public void suspendProcess(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID
    );

    @WebMethod(operationName = "ImportProcessDefinition", action = "urn:WorkflowService.service.livelink.opentext.com/ImportProcessDefinition")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ImportProcessDefinition", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ImportProcessDefinitionResponse")
    @RequestWrapper(localName = "ImportProcessDefinition", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ImportProcessDefinition")
    @ResponseWrapper(localName = "ImportProcessDefinitionResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ImportProcessDefinitionResponse")
    @WebResult(name = "ImportProcessDefinitionResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessDefinition importProcessDefinition(
        @WebParam(name = "parentID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long parentID,
        @WebParam(name = "name", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String name,
        @WebParam(name = "comment", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String comment,
        @WebParam(name = "attachmentData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        boolean attachmentData,
        @WebParam(name = "resetMembers", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        boolean resetMembers,
        @WebParam(name = "attach", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.core.Attachment attach
    );

    @WebMethod(operationName = "SendWorkItemForSubmapReview", action = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForSubmapReview")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForSubmapReview", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/SendWorkItemForSubmapReviewResponse")
    @RequestWrapper(localName = "SendWorkItemForSubmapReview", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForSubmapReview")
    @ResponseWrapper(localName = "SendWorkItemForSubmapReviewResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForSubmapReviewResponse")
    public void sendWorkItemForSubmapReview(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "submapID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long submapID
    );

    @WebMethod(operationName = "UpdateWorkItemData", action = "urn:WorkflowService.service.livelink.opentext.com/UpdateWorkItemData")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/UpdateWorkItemData", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/UpdateWorkItemDataResponse")
    @RequestWrapper(localName = "UpdateWorkItemData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.UpdateWorkItemData")
    @ResponseWrapper(localName = "UpdateWorkItemDataResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.UpdateWorkItemDataResponse")
    public void updateWorkItemData(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "applicationData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.util.List<com.opentext.livelink.service.workflowservice.ApplicationData> applicationData
    );

    @WebMethod(operationName = "SendWorkItemForUserReview", action = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForUserReview")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForUserReview", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/SendWorkItemForUserReviewResponse")
    @RequestWrapper(localName = "SendWorkItemForUserReview", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForUserReview")
    @ResponseWrapper(localName = "SendWorkItemForUserReviewResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForUserReviewResponse")
    public void sendWorkItemForUserReview(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "userID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long userID,
        @WebParam(name = "title", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String title,
        @WebParam(name = "instructions", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String instructions,
        @WebParam(name = "duration", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int duration,
        @WebParam(name = "priority", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.workflowservice.WorkItemPriority priority
    );

    @WebMethod(operationName = "ResumeProcess", action = "urn:WorkflowService.service.livelink.opentext.com/ResumeProcess")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ResumeProcess", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ResumeProcessResponse")
    @RequestWrapper(localName = "ResumeProcess", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ResumeProcess")
    @ResponseWrapper(localName = "ResumeProcessResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ResumeProcessResponse")
    public void resumeProcess(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID
    );

    @WebMethod(operationName = "AcceptWorkItem", action = "urn:WorkflowService.service.livelink.opentext.com/AcceptWorkItem")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/AcceptWorkItem", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/AcceptWorkItemResponse")
    @RequestWrapper(localName = "AcceptWorkItem", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.AcceptWorkItem")
    @ResponseWrapper(localName = "AcceptWorkItemResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.AcceptWorkItemResponse")
    public void acceptWorkItem(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID
    );

    @WebMethod(operationName = "ArchiveProcess", action = "urn:WorkflowService.service.livelink.opentext.com/ArchiveProcess")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ArchiveProcess", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ArchiveProcessResponse")
    @RequestWrapper(localName = "ArchiveProcess", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ArchiveProcess")
    @ResponseWrapper(localName = "ArchiveProcessResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ArchiveProcessResponse")
    public void archiveProcess(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID
    );

    @WebMethod(operationName = "ListProcessHistory", action = "urn:WorkflowService.service.livelink.opentext.com/ListProcessHistory")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ListProcessHistory", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ListProcessHistoryResponse")
    @RequestWrapper(localName = "ListProcessHistory", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListProcessHistory")
    @ResponseWrapper(localName = "ListProcessHistoryResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListProcessHistoryResponse")
    @WebResult(name = "ListProcessHistoryResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.workflowservice.ProcessEvent> listProcessHistory(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.Integer activityID
    );

    @WebMethod(operationName = "CreateProcess", action = "urn:WorkflowService.service.livelink.opentext.com/CreateProcess")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/CreateProcess", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/CreateProcessResponse")
    @RequestWrapper(localName = "CreateProcess", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.CreateProcess")
    @ResponseWrapper(localName = "CreateProcessResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.CreateProcessResponse")
    @WebResult(name = "CreateProcessResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessInstance createProcess(
        @WebParam(name = "processDef", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.workflowservice.ProcessDefinition processDef,
        @WebParam(name = "processName", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String processName,
        @WebParam(name = "attachments", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.util.List<java.lang.Long> attachments,
        @WebParam(name = "memberRoleIDs", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.util.List<java.lang.Long> memberRoleIDs
    );

    @WebMethod(operationName = "SendWorkItemForReview", action = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForReview")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForReview", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/SendWorkItemForReviewResponse")
    @RequestWrapper(localName = "SendWorkItemForReview", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForReview")
    @ResponseWrapper(localName = "SendWorkItemForReviewResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForReviewResponse")
    public void sendWorkItemForReview(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "memberID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long memberID,
        @WebParam(name = "title", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String title,
        @WebParam(name = "instructions", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String instructions,
        @WebParam(name = "duration", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int duration
    );

    @WebMethod(operationName = "DelegateWorkItem", action = "urn:WorkflowService.service.livelink.opentext.com/DelegateWorkItem")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/DelegateWorkItem", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/DelegateWorkItemResponse")
    @RequestWrapper(localName = "DelegateWorkItem", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.DelegateWorkItem")
    @ResponseWrapper(localName = "DelegateWorkItemResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.DelegateWorkItemResponse")
    public void delegateWorkItem(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "memberID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long memberID
    );

    @WebMethod(operationName = "GetProcessDefinitionEx", action = "urn:WorkflowService.service.livelink.opentext.com/GetProcessDefinitionEx")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetProcessDefinitionEx", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetProcessDefinitionExResponse")
    @RequestWrapper(localName = "GetProcessDefinitionEx", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessDefinitionEx")
    @ResponseWrapper(localName = "GetProcessDefinitionExResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessDefinitionExResponse")
    @WebResult(name = "GetProcessDefinitionExResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessDefinition getProcessDefinitionEx(
        @WebParam(name = "objectID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long objectID
    );

    @WebMethod(operationName = "GetProcessStartData", action = "urn:WorkflowService.service.livelink.opentext.com/GetProcessStartData")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetProcessStartData", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetProcessStartDataResponse")
    @RequestWrapper(localName = "GetProcessStartData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessStartData")
    @ResponseWrapper(localName = "GetProcessStartDataResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessStartDataResponse")
    @WebResult(name = "GetProcessStartDataResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessStartData getProcessStartData(
        @WebParam(name = "objectID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long objectID
    );

    @WebMethod(operationName = "ReassignActivity", action = "urn:WorkflowService.service.livelink.opentext.com/ReassignActivity")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ReassignActivity", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ReassignActivityResponse")
    @RequestWrapper(localName = "ReassignActivity", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ReassignActivity")
    @ResponseWrapper(localName = "ReassignActivityResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ReassignActivityResponse")
    public void reassignActivity(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "memberID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long memberID
    );

    @WebMethod(operationName = "GetListProcessesResults", action = "urn:WorkflowService.service.livelink.opentext.com/GetListProcessesResults")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetListProcessesResults", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetListProcessesResultsResponse")
    @RequestWrapper(localName = "GetListProcessesResults", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetListProcessesResults")
    @ResponseWrapper(localName = "GetListProcessesResultsResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetListProcessesResultsResponse")
    @WebResult(name = "GetListProcessesResultsResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessResult getListProcessesResults(
        @WebParam(name = "pageHandle", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.core.PageHandle pageHandle
    );

    @WebMethod(operationName = "DeleteProcess", action = "urn:WorkflowService.service.livelink.opentext.com/DeleteProcess")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/DeleteProcess", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/DeleteProcessResponse")
    @RequestWrapper(localName = "DeleteProcess", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.DeleteProcess")
    @ResponseWrapper(localName = "DeleteProcessResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.DeleteProcessResponse")
    public void deleteProcess(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID
    );

    @WebMethod(operationName = "CompleteWorkItem", action = "urn:WorkflowService.service.livelink.opentext.com/CompleteWorkItem")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/CompleteWorkItem", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/CompleteWorkItemResponse")
    @RequestWrapper(localName = "CompleteWorkItem", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.CompleteWorkItem")
    @ResponseWrapper(localName = "CompleteWorkItemResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.CompleteWorkItemResponse")
    public void completeWorkItem(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "disposition", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String disposition
    );

    @WebMethod(operationName = "ListWorkItems", action = "urn:WorkflowService.service.livelink.opentext.com/ListWorkItems")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ListWorkItems", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ListWorkItemsResponse")
    @RequestWrapper(localName = "ListWorkItems", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListWorkItems")
    @ResponseWrapper(localName = "ListWorkItemsResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListWorkItemsResponse")
    @WebResult(name = "ListWorkItemsResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.WorkItemResult listWorkItems(
        @WebParam(name = "pageHandle", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.core.PageHandle pageHandle
    );

    @WebMethod(operationName = "ListWorkItemsEx", action = "urn:WorkflowService.service.livelink.opentext.com/ListWorkItemsEx")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ListWorkItemsEx", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ListWorkItemsExResponse")
    @RequestWrapper(localName = "ListWorkItemsEx", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListWorkItemsEx")
    @ResponseWrapper(localName = "ListWorkItemsExResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListWorkItemsExResponse")
    @WebResult(name = "ListWorkItemsExResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.WorkItemResult listWorkItemsEx(
        @WebParam(name = "pageHandle", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.core.PageHandle pageHandle
    );

    @WebMethod(operationName = "GetWorkItemDetails", action = "urn:WorkflowService.service.livelink.opentext.com/GetWorkItemDetails")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetWorkItemDetails", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetWorkItemDetailsResponse")
    @RequestWrapper(localName = "GetWorkItemDetails", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetWorkItemDetails")
    @ResponseWrapper(localName = "GetWorkItemDetailsResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetWorkItemDetailsResponse")
    @WebResult(name = "GetWorkItemDetailsResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.WorkItemDetails getWorkItemDetails(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID
    );

    @WebMethod(operationName = "StartProcess", action = "urn:WorkflowService.service.livelink.opentext.com/StartProcess")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/StartProcess", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/StartProcessResponse")
    @RequestWrapper(localName = "StartProcess", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.StartProcess")
    @ResponseWrapper(localName = "StartProcessResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.StartProcessResponse")
    @WebResult(name = "StartProcessResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessInstance startProcess(
        @WebParam(name = "startData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.workflowservice.ProcessStartData startData,
        @WebParam(name = "attachments", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.util.List<java.lang.Long> attachments,
        @WebParam(name = "memberRoleIDs", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.util.List<java.lang.Long> memberRoleIDs
    );

    @WebMethod(operationName = "GetProcessData", action = "urn:WorkflowService.service.livelink.opentext.com/GetProcessData")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetProcessData", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetProcessDataResponse")
    @RequestWrapper(localName = "GetProcessData", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessData")
    @ResponseWrapper(localName = "GetProcessDataResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessDataResponse")
    @WebResult(name = "GetProcessDataResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.workflowservice.ApplicationData> getProcessData(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID
    );

    @WebMethod(operationName = "SendWorkItemForGroupReview", action = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForGroupReview")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/SendWorkItemForGroupReview", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/SendWorkItemForGroupReviewResponse")
    @RequestWrapper(localName = "SendWorkItemForGroupReview", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForGroupReview")
    @ResponseWrapper(localName = "SendWorkItemForGroupReviewResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.SendWorkItemForGroupReviewResponse")
    public void sendWorkItemForGroupReview(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID,
        @WebParam(name = "activityID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int activityID,
        @WebParam(name = "groupID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long groupID,
        @WebParam(name = "title", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String title,
        @WebParam(name = "instructions", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        java.lang.String instructions,
        @WebParam(name = "duration", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        int duration,
        @WebParam(name = "priority", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.workflowservice.WorkItemPriority priority,
        @WebParam(name = "groupOptions", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.workflowservice.GroupOptions groupOptions
    );

    @WebMethod(operationName = "GetProcessStatus", action = "urn:WorkflowService.service.livelink.opentext.com/GetProcessStatus")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/GetProcessStatus", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/GetProcessStatusResponse")
    @RequestWrapper(localName = "GetProcessStatus", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessStatus")
    @ResponseWrapper(localName = "GetProcessStatusResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.GetProcessStatusResponse")
    @WebResult(name = "GetProcessStatusResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.workflowservice.ProcessInstance getProcessStatus(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID,
        @WebParam(name = "subProcessID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long subProcessID
    );

    @WebMethod(operationName = "StopProcess", action = "urn:WorkflowService.service.livelink.opentext.com/StopProcess")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/StopProcess", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/StopProcessResponse")
    @RequestWrapper(localName = "StopProcess", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.StopProcess")
    @ResponseWrapper(localName = "StopProcessResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.StopProcessResponse")
    public void stopProcess(
        @WebParam(name = "processID", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        long processID
    );

    @WebMethod(operationName = "ListProcesses", action = "urn:WorkflowService.service.livelink.opentext.com/ListProcesses")
    @Action(input = "urn:WorkflowService.service.livelink.opentext.com/ListProcesses", output = "urn:WorkflowService.service.livelink.opentext.com/WorkflowService/ListProcessesResponse")
    @RequestWrapper(localName = "ListProcesses", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListProcesses")
    @ResponseWrapper(localName = "ListProcessesResponse", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com", className = "com.opentext.livelink.service.workflowservice.ListProcessesResponse")
    @WebResult(name = "ListProcessesResult", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
    public com.opentext.livelink.service.core.PageHandle listProcesses(
        @WebParam(name = "options", targetNamespace = "urn:WorkflowService.service.livelink.opentext.com")
        com.opentext.livelink.service.workflowservice.ProcessSearchOptions options
    );
}
