var nesToc=new String(';'+
'1:copyrght;'+
'2:sync-icons-bg;'+
'2-1:syncpc-filter-p;'+
'2-2:syncpcwb-sortfolder-p;'+
'2-3:syncpcwb-switchthumbnail-p;'+
'2-4:syncpcwb-logout-p;'+
'3:syncpcwb-fileman-so;'+
'3-1:syncpcwb-createfolder-p;'+
'3-2:syncpcwb-folderdesc-p;'+
'3-3:syncpcwb-uploadfile-p;'+
'3-4:syncpcwb-addversion-p;'+
'3-5:syncpcwb-downloadfile-p;'+
'3-6:syncpcwb-copymove-p;'+
'3-7:syncpcwb-rename-p;'+
'3-8:syncpcwb-reserve-p;'+
'3-9:syncpcwb-brava-p;'+
'3-10:syncpcwb-delete-p;'+
'3-11:syncpcwb-delete-shared-folder-p;'+
'3-12:syncpcwb-viewhistory-p;'+
'3-13:syncpcwb-publish-p;'+
'3-14:syncpcwb-search-p;'+
'3-15:syncpcwb-checkfoldersize-p;'+
'4:syncpcwb-sharing-so;'+
'4-1:synclles-invite-ext-user-p;'+
'4-2:syncpcwb-acceptsharereq-p;'+
'4-3:syncpcwb-readonlyshare-p;'+
'4-4:syncpcwb-unsharefolder-p;'+
'4-5:syncpcwb-emailnotsharedfolder-p;'+
'4-6:syncpc-renamedelmoveshare-bg;'+
'5:syncpcwb-tasks-so;'+
'5-1:syncpcwb-viewtask-p;'+
'5-2:syncpcwb-createtask-p;'+
'5-3:syncpcwb-updatestatus-p;'+
'5-4:syncpcwb-deletetask-p;'+
'6:syncpcwb-settings-so;'+
'6-1:syncpcwb-updatephoto-p;'+
'6-2:syncpcwb-enableemailnot-p;'+
'6-3:syncpcwb-changepwexternal-p;'+
'6-4:syncpcwb-viewversion-p;'+
'');
var dojstocl=0;
