package com.opentext.livelink.service.searchservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:09:50.259-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:SearchServices.service.livelink.opentext.com", name = "SearchService")
@XmlSeeAlso({ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface SearchService {

    @WebMethod(operationName = "GetFieldInfo", action = "urn:SearchServices.service.livelink.opentext.com/GetFieldInfo")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/GetFieldInfo", output = "urn:SearchServices.service.livelink.opentext.com/SearchService/GetFieldInfoResponse")
    @RequestWrapper(localName = "GetFieldInfo", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetFieldInfo")
    @ResponseWrapper(localName = "GetFieldInfoResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetFieldInfoResponse")
    @WebResult(name = "GetFieldInfoResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.searchservices.FieldInfo> getFieldInfo(
        @WebParam(name = "dataCollection", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String dataCollection,
        @WebParam(name = "fieldhints", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.util.List<java.lang.String> fieldhints
    );

    @WebMethod(operationName = "GetDataCollections", action = "urn:SearchServices.service.livelink.opentext.com/GetDataCollections")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/GetDataCollections", output = "urn:SearchServices.service.livelink.opentext.com/SearchService/GetDataCollectionsResponse")
    @RequestWrapper(localName = "GetDataCollections", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetDataCollections")
    @ResponseWrapper(localName = "GetDataCollectionsResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetDataCollectionsResponse")
    @WebResult(name = "GetDataCollectionsResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public java.util.List<java.lang.String> getDataCollections();

    @WebMethod(operationName = "GetQueryLanguageDescription", action = "urn:SearchServices.service.livelink.opentext.com/GetQueryLanguageDescription")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/GetQueryLanguageDescription", output = "urn:SearchServices.service.livelink.opentext.com/SearchService/GetQueryLanguageDescriptionResponse")
    @RequestWrapper(localName = "GetQueryLanguageDescription", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetQueryLanguageDescription")
    @ResponseWrapper(localName = "GetQueryLanguageDescriptionResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetQueryLanguageDescriptionResponse")
    @WebResult(name = "GetQueryLanguageDescriptionResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public java.lang.String getQueryLanguageDescription(
        @WebParam(name = "iso639LanguageCode", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String iso639LanguageCode,
        @WebParam(name = "queryLanguage", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String queryLanguage
    );

    @WebMethod(operationName = "GetResultPageDescription", action = "urn:SearchServices.service.livelink.opentext.com/GetResultPageDescription")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/GetResultPageDescription", output = "urn:SearchServices.service.livelink.opentext.com/SearchService/GetResultPageDescriptionResponse")
    @RequestWrapper(localName = "GetResultPageDescription", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetResultPageDescription")
    @ResponseWrapper(localName = "GetResultPageDescriptionResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetResultPageDescriptionResponse")
    @WebResult(name = "GetResultPageDescriptionResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public java.lang.String getResultPageDescription(
        @WebParam(name = "iso639LanguageCode", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String iso639LanguageCode,
        @WebParam(name = "queryLanguage", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String queryLanguage
    );

    @WebMethod(operationName = "GetSupportedQueryLanguages", action = "urn:SearchServices.service.livelink.opentext.com/GetSupportedQueryLanguages")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/GetSupportedQueryLanguages", output = "urn:SearchServices.service.livelink.opentext.com/SearchService/GetSupportedQueryLanguagesResponse")
    @RequestWrapper(localName = "GetSupportedQueryLanguages", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetSupportedQueryLanguages")
    @ResponseWrapper(localName = "GetSupportedQueryLanguagesResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetSupportedQueryLanguagesResponse")
    @WebResult(name = "GetSupportedQueryLanguagesResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public java.util.List<java.lang.String> getSupportedQueryLanguages();

    @WebMethod(operationName = "Search", action = "urn:SearchServices.service.livelink.opentext.com/Search")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/Search", output = "urn:SearchServices.service.livelink.opentext.com/SearchService/SearchResponse")
    @RequestWrapper(localName = "Search", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.SearchResponse")
    @WebResult(name = "SearchResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public com.opentext.livelink.service.searchservices.SingleSearchResponse search(
        @WebParam(name = "queries", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        com.opentext.livelink.service.searchservices.SingleSearchRequest queries,
        @WebParam(name = "partitionName", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String partitionName
    );
}
