package com.opentext.livelink.service.core;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:16:54.537-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:Core.service.livelink.opentext.com", name = "XmlService")
@XmlSeeAlso({ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface XmlService {

    @WebMethod(operationName = "ExportXml", action = "urn:Core.service.livelink.opentext.com/ExportXml")
    @Action(input = "urn:Core.service.livelink.opentext.com/ExportXml", output = "urn:Core.service.livelink.opentext.com/XmlService/ExportXmlResponse")
    @RequestWrapper(localName = "ExportXml", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ExportXml")
    @ResponseWrapper(localName = "ExportXmlResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ExportXmlResponse")
    @WebResult(name = "ExportXmlResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public com.opentext.livelink.service.core.Attachment exportXml(
        @WebParam(name = "nodeID", targetNamespace = "urn:Core.service.livelink.opentext.com")
        long nodeID,
        @WebParam(name = "options", targetNamespace = "urn:Core.service.livelink.opentext.com")
        com.opentext.livelink.service.core.ExportOptions options
    );

    @WebMethod(operationName = "ExportXmlContext", action = "urn:Core.service.livelink.opentext.com/ExportXmlContext")
    @Action(input = "urn:Core.service.livelink.opentext.com/ExportXmlContext", output = "urn:Core.service.livelink.opentext.com/XmlService/ExportXmlContextResponse")
    @RequestWrapper(localName = "ExportXmlContext", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ExportXmlContext")
    @ResponseWrapper(localName = "ExportXmlContextResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ExportXmlContextResponse")
    @WebResult(name = "ExportXmlContextResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String exportXmlContext(
        @WebParam(name = "nodeID", targetNamespace = "urn:Core.service.livelink.opentext.com")
        long nodeID,
        @WebParam(name = "options", targetNamespace = "urn:Core.service.livelink.opentext.com")
        com.opentext.livelink.service.core.ExportOptions options
    );

    @WebMethod(operationName = "ImportXmlContext", action = "urn:Core.service.livelink.opentext.com/ImportXmlContext")
    @Action(input = "urn:Core.service.livelink.opentext.com/ImportXmlContext", output = "urn:Core.service.livelink.opentext.com/XmlService/ImportXmlContextResponse")
    @RequestWrapper(localName = "ImportXmlContext", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImportXmlContext")
    @ResponseWrapper(localName = "ImportXmlContextResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImportXmlContextResponse")
    @WebResult(name = "ImportXmlContextResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String importXmlContext(
        @WebParam(name = "nodeID", targetNamespace = "urn:Core.service.livelink.opentext.com")
        long nodeID,
        @WebParam(name = "options", targetNamespace = "urn:Core.service.livelink.opentext.com")
        com.opentext.livelink.service.core.ImportOptions options
    );

    @WebMethod(operationName = "ImportXml", action = "urn:Core.service.livelink.opentext.com/ImportXml")
    @Action(input = "urn:Core.service.livelink.opentext.com/ImportXml", output = "urn:Core.service.livelink.opentext.com/XmlService/ImportXmlResponse")
    @RequestWrapper(localName = "ImportXml", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImportXml")
    @ResponseWrapper(localName = "ImportXmlResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImportXmlResponse")
    @WebResult(name = "ImportXmlResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public long importXml(
        @WebParam(name = "nodeID", targetNamespace = "urn:Core.service.livelink.opentext.com")
        long nodeID,
        @WebParam(name = "options", targetNamespace = "urn:Core.service.livelink.opentext.com")
        com.opentext.livelink.service.core.ImportOptions options,
        @WebParam(name = "attach", targetNamespace = "urn:Core.service.livelink.opentext.com")
        com.opentext.livelink.service.core.Attachment attach
    );
}
