package com.opentext.livelink.service.core;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:16:54.567-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "XmlService", 
                  wsdlLocation = "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-xml-service-ws/src/main/resources/XmlService.wsdl",
                  targetNamespace = "urn:Core.service.livelink.opentext.com") 
public class XmlService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:Core.service.livelink.opentext.com", "XmlService");
    public final static QName BasicHttpBindingXmlService = new QName("urn:Core.service.livelink.opentext.com", "BasicHttpBinding_XmlService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-xml-service-ws/src/main/resources/XmlService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(XmlService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-xml-service-ws/src/main/resources/XmlService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public XmlService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public XmlService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public XmlService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public XmlService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public XmlService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public XmlService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns XmlService
     */
    @WebEndpoint(name = "BasicHttpBinding_XmlService")
    public XmlService getBasicHttpBindingXmlService() {
        return super.getPort(BasicHttpBindingXmlService, XmlService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns XmlService
     */
    @WebEndpoint(name = "BasicHttpBinding_XmlService")
    public XmlService getBasicHttpBindingXmlService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingXmlService, XmlService.class, features);
    }

}
