package com.opentext.livelink.service.collaboration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:05:26.692-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:Collaboration.service.livelink.opentext.com", name = "Collaboration")
@XmlSeeAlso({com.opentext.livelink.service.core.ObjectFactory.class, com.opentext.livelink.service.docman.ObjectFactory.class, com.opentext.livelink.service.memberservice.ObjectFactory.class, ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface Collaboration {

    @WebMethod(operationName = "ListTopics", action = "urn:Collaboration.service.livelink.opentext.com/ListTopics")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/ListTopics", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/ListTopicsResponse")
    @RequestWrapper(localName = "ListTopics", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListTopics")
    @ResponseWrapper(localName = "ListTopicsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListTopicsResponse")
    @WebResult(name = "ListTopicsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.TopicInfo> listTopics(
        @WebParam(name = "discussionID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long discussionID
    );

    @WebMethod(operationName = "GetChannel", action = "urn:Collaboration.service.livelink.opentext.com/GetChannel")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetChannel", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetChannelResponse")
    @RequestWrapper(localName = "GetChannel", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetChannel")
    @ResponseWrapper(localName = "GetChannelResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetChannelResponse")
    @WebResult(name = "GetChannelResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.ChannelInfo getChannel(
        @WebParam(name = "channelID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long channelID
    );

    @WebMethod(operationName = "CreateTaskGroup", action = "urn:Collaboration.service.livelink.opentext.com/CreateTaskGroup")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateTaskGroup", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateTaskGroupResponse")
    @RequestWrapper(localName = "CreateTaskGroup", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateTaskGroup")
    @ResponseWrapper(localName = "CreateTaskGroupResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateTaskGroupResponse")
    @WebResult(name = "CreateTaskGroupResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createTaskGroup(
        @WebParam(name = "taskGroupInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.TaskGroupInfo taskGroupInfo
    );

    @WebMethod(operationName = "GetTaskGroup", action = "urn:Collaboration.service.livelink.opentext.com/GetTaskGroup")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetTaskGroup", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetTaskGroupResponse")
    @RequestWrapper(localName = "GetTaskGroup", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTaskGroup")
    @ResponseWrapper(localName = "GetTaskGroupResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTaskGroupResponse")
    @WebResult(name = "GetTaskGroupResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.TaskGroupInfo getTaskGroup(
        @WebParam(name = "taskGroupID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long taskGroupID
    );

    @WebMethod(operationName = "CreateProject", action = "urn:Collaboration.service.livelink.opentext.com/CreateProject")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateProject", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateProjectResponse")
    @RequestWrapper(localName = "CreateProject", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateProject")
    @ResponseWrapper(localName = "CreateProjectResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateProjectResponse")
    @WebResult(name = "CreateProjectResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createProject(
        @WebParam(name = "projectInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.ProjectInfo projectInfo
    );

    @WebMethod(operationName = "GetMyProjects", action = "urn:Collaboration.service.livelink.opentext.com/GetMyProjects")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetMyProjects", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetMyProjectsResponse")
    @RequestWrapper(localName = "GetMyProjects", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyProjects")
    @ResponseWrapper(localName = "GetMyProjectsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyProjectsResponse")
    @WebResult(name = "GetMyProjectsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.ProjectInfo> getMyProjects();

    @WebMethod(operationName = "GetMyChannels", action = "urn:Collaboration.service.livelink.opentext.com/GetMyChannels")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetMyChannels", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetMyChannelsResponse")
    @RequestWrapper(localName = "GetMyChannels", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyChannels")
    @ResponseWrapper(localName = "GetMyChannelsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyChannelsResponse")
    @WebResult(name = "GetMyChannelsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.ChannelInfo> getMyChannels();

    @WebMethod(operationName = "GetUnreadInfo", action = "urn:Collaboration.service.livelink.opentext.com/GetUnreadInfo")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetUnreadInfo", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetUnreadInfoResponse")
    @RequestWrapper(localName = "GetUnreadInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetUnreadInfo")
    @ResponseWrapper(localName = "GetUnreadInfoResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetUnreadInfoResponse")
    @WebResult(name = "GetUnreadInfoResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.UnreadInfo> getUnreadInfo(
        @WebParam(name = "ids", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.util.List<java.lang.Long> ids
    );

    @WebMethod(operationName = "CreateDiscussion", action = "urn:Collaboration.service.livelink.opentext.com/CreateDiscussion")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateDiscussion", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateDiscussionResponse")
    @RequestWrapper(localName = "CreateDiscussion", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateDiscussion")
    @ResponseWrapper(localName = "CreateDiscussionResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateDiscussionResponse")
    @WebResult(name = "CreateDiscussionResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createDiscussion(
        @WebParam(name = "discussionInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.DiscussionInfo discussionInfo
    );

    @WebMethod(operationName = "GetNews", action = "urn:Collaboration.service.livelink.opentext.com/GetNews")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetNews", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetNewsResponse")
    @RequestWrapper(localName = "GetNews", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetNews")
    @ResponseWrapper(localName = "GetNewsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetNewsResponse")
    @WebResult(name = "GetNewsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.NewsInfo getNews(
        @WebParam(name = "newsID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long newsID
    );

    @WebMethod(operationName = "GetTaskList", action = "urn:Collaboration.service.livelink.opentext.com/GetTaskList")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetTaskList", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetTaskListResponse")
    @RequestWrapper(localName = "GetTaskList", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTaskList")
    @ResponseWrapper(localName = "GetTaskListResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTaskListResponse")
    @WebResult(name = "GetTaskListResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.TaskListInfo getTaskList(
        @WebParam(name = "taskListID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long taskListID
    );

    @WebMethod(operationName = "CreateChannel", action = "urn:Collaboration.service.livelink.opentext.com/CreateChannel")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateChannel", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateChannelResponse")
    @RequestWrapper(localName = "CreateChannel", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateChannel")
    @ResponseWrapper(localName = "CreateChannelResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateChannelResponse")
    @WebResult(name = "CreateChannelResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createChannel(
        @WebParam(name = "channelInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.ChannelInfo channelInfo
    );

    @WebMethod(operationName = "ListTaskGroups", action = "urn:Collaboration.service.livelink.opentext.com/ListTaskGroups")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/ListTaskGroups", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/ListTaskGroupsResponse")
    @RequestWrapper(localName = "ListTaskGroups", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListTaskGroups")
    @ResponseWrapper(localName = "ListTaskGroupsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListTaskGroupsResponse")
    @WebResult(name = "ListTaskGroupsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.TaskGroupInfo> listTaskGroups(
        @WebParam(name = "ID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long id
    );

    @WebMethod(operationName = "PostReply", action = "urn:Collaboration.service.livelink.opentext.com/PostReply")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/PostReply", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/PostReplyResponse")
    @RequestWrapper(localName = "PostReply", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.PostReply")
    @ResponseWrapper(localName = "PostReplyResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.PostReplyResponse")
    @WebResult(name = "PostReplyResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.ReplyInfo postReply(
        @WebParam(name = "topicReply", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long topicReply,
        @WebParam(name = "subject", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.String subject,
        @WebParam(name = "comments", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.String comments,
        @WebParam(name = "livelinkAttachment", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.Long livelinkAttachment,
        @WebParam(name = "attach", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.core.Attachment attach
    );

    @WebMethod(operationName = "UpdateProjectParticipants", action = "urn:Collaboration.service.livelink.opentext.com/UpdateProjectParticipants")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/UpdateProjectParticipants", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/UpdateProjectParticipantsResponse")
    @RequestWrapper(localName = "UpdateProjectParticipants", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateProjectParticipants")
    @ResponseWrapper(localName = "UpdateProjectParticipantsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateProjectParticipantsResponse")
    public void updateProjectParticipants(
        @WebParam(name = "projectID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long projectID,
        @WebParam(name = "roleUpdateInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.util.List<com.opentext.livelink.service.collaboration.ProjectRoleUpdateInfo> roleUpdateInfo
    );

    @WebMethod(operationName = "UpdateTask", action = "urn:Collaboration.service.livelink.opentext.com/UpdateTask")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/UpdateTask", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/UpdateTaskResponse")
    @RequestWrapper(localName = "UpdateTask", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateTask")
    @ResponseWrapper(localName = "UpdateTaskResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateTaskResponse")
    public void updateTask(
        @WebParam(name = "taskInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.TaskInfo taskInfo
    );

    @WebMethod(operationName = "GetReadList", action = "urn:Collaboration.service.livelink.opentext.com/GetReadList")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetReadList", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetReadListResponse")
    @RequestWrapper(localName = "GetReadList", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetReadList")
    @ResponseWrapper(localName = "GetReadListResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetReadListResponse")
    @WebResult(name = "GetReadListResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.DiscussionReadList> getReadList(
        @WebParam(name = "discussionID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long discussionID
    );

    @WebMethod(operationName = "GetTopicByName", action = "urn:Collaboration.service.livelink.opentext.com/GetTopicByName")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetTopicByName", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetTopicByNameResponse")
    @RequestWrapper(localName = "GetTopicByName", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTopicByName")
    @ResponseWrapper(localName = "GetTopicByNameResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTopicByNameResponse")
    @WebResult(name = "GetTopicByNameResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.TopicInfo getTopicByName(
        @WebParam(name = "discussionID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long discussionID,
        @WebParam(name = "name", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.String name
    );

    @WebMethod(operationName = "CreateNews", action = "urn:Collaboration.service.livelink.opentext.com/CreateNews")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateNews", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateNewsResponse")
    @RequestWrapper(localName = "CreateNews", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateNews")
    @ResponseWrapper(localName = "CreateNewsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateNewsResponse")
    @WebResult(name = "CreateNewsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createNews(
        @WebParam(name = "newsInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.NewsInfo newsInfo,
        @WebParam(name = "livelinkAttachment", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.Long livelinkAttachment,
        @WebParam(name = "attach", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.core.Attachment attach
    );

    @WebMethod(operationName = "GetTask", action = "urn:Collaboration.service.livelink.opentext.com/GetTask")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetTask", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetTaskResponse")
    @RequestWrapper(localName = "GetTask", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTask")
    @ResponseWrapper(localName = "GetTaskResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTaskResponse")
    @WebResult(name = "GetTaskResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.TaskInfo getTask(
        @WebParam(name = "taskID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long taskID
    );

    @WebMethod(operationName = "GetMilestone", action = "urn:Collaboration.service.livelink.opentext.com/GetMilestone")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetMilestone", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetMilestoneResponse")
    @RequestWrapper(localName = "GetMilestone", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMilestone")
    @ResponseWrapper(localName = "GetMilestoneResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMilestoneResponse")
    @WebResult(name = "GetMilestoneResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.MilestoneInfo getMilestone(
        @WebParam(name = "milestoneID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long milestoneID
    );

    @WebMethod(operationName = "ListTasks", action = "urn:Collaboration.service.livelink.opentext.com/ListTasks")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/ListTasks", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/ListTasksResponse")
    @RequestWrapper(localName = "ListTasks", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListTasks")
    @ResponseWrapper(localName = "ListTasksResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListTasksResponse")
    @WebResult(name = "ListTasksResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.TaskInfo> listTasks(
        @WebParam(name = "ID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long id
    );

    @WebMethod(operationName = "ListReplies", action = "urn:Collaboration.service.livelink.opentext.com/ListReplies")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/ListReplies", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/ListRepliesResponse")
    @RequestWrapper(localName = "ListReplies", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListReplies")
    @ResponseWrapper(localName = "ListRepliesResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListRepliesResponse")
    @WebResult(name = "ListRepliesResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.ReplyInfo> listReplies(
        @WebParam(name = "topicReplyID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long topicReplyID
    );

    @WebMethod(operationName = "GetReplyByName", action = "urn:Collaboration.service.livelink.opentext.com/GetReplyByName")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetReplyByName", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetReplyByNameResponse")
    @RequestWrapper(localName = "GetReplyByName", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetReplyByName")
    @ResponseWrapper(localName = "GetReplyByNameResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetReplyByNameResponse")
    @WebResult(name = "GetReplyByNameResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.ReplyInfo getReplyByName(
        @WebParam(name = "topicReplyID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long topicReplyID,
        @WebParam(name = "name", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.String name
    );

    @WebMethod(operationName = "GetProject", action = "urn:Collaboration.service.livelink.opentext.com/GetProject")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetProject", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetProjectResponse")
    @RequestWrapper(localName = "GetProject", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetProject")
    @ResponseWrapper(localName = "GetProjectResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetProjectResponse")
    @WebResult(name = "GetProjectResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.ProjectInfo getProject(
        @WebParam(name = "projectID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long projectID
    );

    @WebMethod(operationName = "CreateTask", action = "urn:Collaboration.service.livelink.opentext.com/CreateTask")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateTask", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateTaskResponse")
    @RequestWrapper(localName = "CreateTask", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateTask")
    @ResponseWrapper(localName = "CreateTaskResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateTaskResponse")
    @WebResult(name = "CreateTaskResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createTask(
        @WebParam(name = "taskInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.TaskInfo taskInfo
    );

    @WebMethod(operationName = "CreateTaskList", action = "urn:Collaboration.service.livelink.opentext.com/CreateTaskList")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateTaskList", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateTaskListResponse")
    @RequestWrapper(localName = "CreateTaskList", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateTaskList")
    @ResponseWrapper(localName = "CreateTaskListResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateTaskListResponse")
    @WebResult(name = "CreateTaskListResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createTaskList(
        @WebParam(name = "taskListInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.TaskListInfo taskListInfo
    );

    @WebMethod(operationName = "UpdateTaskGroup", action = "urn:Collaboration.service.livelink.opentext.com/UpdateTaskGroup")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/UpdateTaskGroup", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/UpdateTaskGroupResponse")
    @RequestWrapper(localName = "UpdateTaskGroup", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateTaskGroup")
    @ResponseWrapper(localName = "UpdateTaskGroupResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateTaskGroupResponse")
    public void updateTaskGroup(
        @WebParam(name = "taskGroupInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.TaskGroupInfo taskGroupInfo
    );

    @WebMethod(operationName = "GetMyTaskLists", action = "urn:Collaboration.service.livelink.opentext.com/GetMyTaskLists")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetMyTaskLists", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetMyTaskListsResponse")
    @RequestWrapper(localName = "GetMyTaskLists", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyTaskLists")
    @ResponseWrapper(localName = "GetMyTaskListsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyTaskListsResponse")
    @WebResult(name = "GetMyTaskListsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.TaskListInfo> getMyTaskLists();

    @WebMethod(operationName = "GetParticipants", action = "urn:Collaboration.service.livelink.opentext.com/GetParticipants")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetParticipants", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetParticipantsResponse")
    @RequestWrapper(localName = "GetParticipants", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetParticipants")
    @ResponseWrapper(localName = "GetParticipantsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetParticipantsResponse")
    @WebResult(name = "GetParticipantsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.ProjectParticipants getParticipants(
        @WebParam(name = "projectID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long projectID
    );

    @WebMethod(operationName = "UpdateProject", action = "urn:Collaboration.service.livelink.opentext.com/UpdateProject")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/UpdateProject", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/UpdateProjectResponse")
    @RequestWrapper(localName = "UpdateProject", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateProject")
    @ResponseWrapper(localName = "UpdateProjectResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateProjectResponse")
    public void updateProject(
        @WebParam(name = "projectInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.ProjectInfo projectInfo
    );

    @WebMethod(operationName = "ListMilestones", action = "urn:Collaboration.service.livelink.opentext.com/ListMilestones")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/ListMilestones", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/ListMilestonesResponse")
    @RequestWrapper(localName = "ListMilestones", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListMilestones")
    @ResponseWrapper(localName = "ListMilestonesResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListMilestonesResponse")
    @WebResult(name = "ListMilestonesResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.MilestoneInfo> listMilestones(
        @WebParam(name = "ID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long id
    );

    @WebMethod(operationName = "SetReadList", action = "urn:Collaboration.service.livelink.opentext.com/SetReadList")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/SetReadList", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/SetReadListResponse")
    @RequestWrapper(localName = "SetReadList", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.SetReadList")
    @ResponseWrapper(localName = "SetReadListResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.SetReadListResponse")
    @WebResult(name = "SetReadListResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.DiscussionReadList> setReadList(
        @WebParam(name = "discussionID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long discussionID,
        @WebParam(name = "readList", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.util.List<com.opentext.livelink.service.collaboration.DiscussionReadList> readList
    );

    @WebMethod(operationName = "UpdateMilestone", action = "urn:Collaboration.service.livelink.opentext.com/UpdateMilestone")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/UpdateMilestone", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/UpdateMilestoneResponse")
    @RequestWrapper(localName = "UpdateMilestone", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateMilestone")
    @ResponseWrapper(localName = "UpdateMilestoneResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateMilestoneResponse")
    public void updateMilestone(
        @WebParam(name = "milestoneInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.MilestoneInfo milestoneInfo
    );

    @WebMethod(operationName = "CreateMilestone", action = "urn:Collaboration.service.livelink.opentext.com/CreateMilestone")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/CreateMilestone", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/CreateMilestoneResponse")
    @RequestWrapper(localName = "CreateMilestone", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateMilestone")
    @ResponseWrapper(localName = "CreateMilestoneResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.CreateMilestoneResponse")
    @WebResult(name = "CreateMilestoneResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.docman.Node createMilestone(
        @WebParam(name = "milestoneInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.MilestoneInfo milestoneInfo
    );

    @WebMethod(operationName = "UpdateNews", action = "urn:Collaboration.service.livelink.opentext.com/UpdateNews")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/UpdateNews", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/UpdateNewsResponse")
    @RequestWrapper(localName = "UpdateNews", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateNews")
    @ResponseWrapper(localName = "UpdateNewsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.UpdateNewsResponse")
    public void updateNews(
        @WebParam(name = "newsInfo", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.collaboration.NewsInfo newsInfo
    );

    @WebMethod(operationName = "GetMyAssignments", action = "urn:Collaboration.service.livelink.opentext.com/GetMyAssignments")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetMyAssignments", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetMyAssignmentsResponse")
    @RequestWrapper(localName = "GetMyAssignments", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyAssignments")
    @ResponseWrapper(localName = "GetMyAssignmentsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyAssignmentsResponse")
    @WebResult(name = "GetMyAssignmentsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.Assignment> getMyAssignments();

    @WebMethod(operationName = "PostTopic", action = "urn:Collaboration.service.livelink.opentext.com/PostTopic")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/PostTopic", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/PostTopicResponse")
    @RequestWrapper(localName = "PostTopic", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.PostTopic")
    @ResponseWrapper(localName = "PostTopicResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.PostTopicResponse")
    @WebResult(name = "PostTopicResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.TopicInfo postTopic(
        @WebParam(name = "discussionID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long discussionID,
        @WebParam(name = "subject", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.String subject,
        @WebParam(name = "comments", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.String comments,
        @WebParam(name = "livelinkAttachment", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        java.lang.Long livelinkAttachment,
        @WebParam(name = "attach", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        com.opentext.livelink.service.core.Attachment attach
    );

    @WebMethod(operationName = "GetTopicReply", action = "urn:Collaboration.service.livelink.opentext.com/GetTopicReply")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetTopicReply", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetTopicReplyResponse")
    @RequestWrapper(localName = "GetTopicReply", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTopicReply")
    @ResponseWrapper(localName = "GetTopicReplyResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetTopicReplyResponse")
    @WebResult(name = "GetTopicReplyResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.DiscussionItem getTopicReply(
        @WebParam(name = "ID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long id
    );

    @WebMethod(operationName = "GetMyDiscussions", action = "urn:Collaboration.service.livelink.opentext.com/GetMyDiscussions")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetMyDiscussions", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetMyDiscussionsResponse")
    @RequestWrapper(localName = "GetMyDiscussions", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyDiscussions")
    @ResponseWrapper(localName = "GetMyDiscussionsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetMyDiscussionsResponse")
    @WebResult(name = "GetMyDiscussionsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.DiscussionInfo> getMyDiscussions();

    @WebMethod(operationName = "GetDiscussion", action = "urn:Collaboration.service.livelink.opentext.com/GetDiscussion")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/GetDiscussion", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/GetDiscussionResponse")
    @RequestWrapper(localName = "GetDiscussion", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetDiscussion")
    @ResponseWrapper(localName = "GetDiscussionResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.GetDiscussionResponse")
    @WebResult(name = "GetDiscussionResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public com.opentext.livelink.service.collaboration.DiscussionInfo getDiscussion(
        @WebParam(name = "discussionID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long discussionID
    );

    @WebMethod(operationName = "ListNews", action = "urn:Collaboration.service.livelink.opentext.com/ListNews")
    @Action(input = "urn:Collaboration.service.livelink.opentext.com/ListNews", output = "urn:Collaboration.service.livelink.opentext.com/Collaboration/ListNewsResponse")
    @RequestWrapper(localName = "ListNews", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListNews")
    @ResponseWrapper(localName = "ListNewsResponse", targetNamespace = "urn:Collaboration.service.livelink.opentext.com", className = "com.opentext.livelink.service.collaboration.ListNewsResponse")
    @WebResult(name = "ListNewsResult", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.collaboration.NewsInfo> listNews(
        @WebParam(name = "channelID", targetNamespace = "urn:Collaboration.service.livelink.opentext.com")
        long channelID
    );
}
