package com.opentext.livelink.service.collaboration;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:05:26.713-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "Collaboration", 
                  wsdlLocation = "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-collaboration-ws/src/main/resources/Collaboration.wsdl",
                  targetNamespace = "urn:Collaboration.service.livelink.opentext.com") 
public class Collaboration_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:Collaboration.service.livelink.opentext.com", "Collaboration");
    public final static QName BasicHttpBindingCollaboration = new QName("urn:Collaboration.service.livelink.opentext.com", "BasicHttpBinding_Collaboration");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-collaboration-ws/src/main/resources/Collaboration.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Collaboration_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-collaboration-ws/src/main/resources/Collaboration.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Collaboration_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Collaboration_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Collaboration_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public Collaboration_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public Collaboration_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public Collaboration_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Collaboration
     */
    @WebEndpoint(name = "BasicHttpBinding_Collaboration")
    public Collaboration getBasicHttpBindingCollaboration() {
        return super.getPort(BasicHttpBindingCollaboration, Collaboration.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Collaboration
     */
    @WebEndpoint(name = "BasicHttpBinding_Collaboration")
    public Collaboration getBasicHttpBindingCollaboration(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingCollaboration, Collaboration.class, features);
    }

}
