package com.opentext.livelink.service.searchservices;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:09:27.284-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:SearchServices.service.livelink.opentext.com", name = "IndexService")
@XmlSeeAlso({ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface IndexService {

    @WebMethod(operationName = "GetObjectsInDateRange", action = "urn:SearchServices.service.livelink.opentext.com/GetObjectsInDateRange")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/GetObjectsInDateRange", output = "urn:SearchServices.service.livelink.opentext.com/IndexService/GetObjectsInDateRangeResponse")
    @RequestWrapper(localName = "GetObjectsInDateRange", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetObjectsInDateRange")
    @ResponseWrapper(localName = "GetObjectsInDateRangeResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.GetObjectsInDateRangeResponse")
    @WebResult(name = "GetObjectsInDateRangeResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public java.util.List<java.lang.String> getObjectsInDateRange(
        @WebParam(name = "fromDate", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        javax.xml.datatype.XMLGregorianCalendar fromDate,
        @WebParam(name = "toDate", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        javax.xml.datatype.XMLGregorianCalendar toDate,
        @WebParam(name = "target", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String target
    );

    @WebMethod(operationName = "ExtractObjects", action = "urn:SearchServices.service.livelink.opentext.com/ExtractObjects")
    @Action(input = "urn:SearchServices.service.livelink.opentext.com/ExtractObjects", output = "urn:SearchServices.service.livelink.opentext.com/IndexService/ExtractObjectsResponse")
    @RequestWrapper(localName = "ExtractObjects", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.ExtractObjects")
    @ResponseWrapper(localName = "ExtractObjectsResponse", targetNamespace = "urn:SearchServices.service.livelink.opentext.com", className = "com.opentext.livelink.service.searchservices.ExtractObjectsResponse")
    @WebResult(name = "ExtractObjectsResult", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
    public com.opentext.livelink.service.searchservices.ExtractResponse extractObjects(
        @WebParam(name = "objects", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.util.List<java.lang.String> objects,
        @WebParam(name = "target", targetNamespace = "urn:SearchServices.service.livelink.opentext.com")
        java.lang.String target
    );
}
