package com.opentext.livelink.service.lesconfig;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:05:29.200-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "ConfigService", 
                  wsdlLocation = "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-config-service-ws/src/main/resources/ConfigService.wsdl",
                  targetNamespace = "urn:LesConfig.service.livelink.opentext.com") 
public class ConfigService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:LesConfig.service.livelink.opentext.com", "ConfigService");
    public final static QName BasicHttpBindingConfigService = new QName("urn:LesConfig.service.livelink.opentext.com", "BasicHttpBinding_ConfigService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-config-service-ws/src/main/resources/ConfigService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ConfigService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-config-service-ws/src/main/resources/ConfigService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ConfigService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ConfigService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConfigService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ConfigService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ConfigService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ConfigService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns ConfigService
     */
    @WebEndpoint(name = "BasicHttpBinding_ConfigService")
    public ConfigService getBasicHttpBindingConfigService() {
        return super.getPort(BasicHttpBindingConfigService, ConfigService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConfigService
     */
    @WebEndpoint(name = "BasicHttpBinding_ConfigService")
    public ConfigService getBasicHttpBindingConfigService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingConfigService, ConfigService.class, features);
    }

}
