package com.opentext.livelink.service.lesconfig;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:05:29.194-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:LesConfig.service.livelink.opentext.com", name = "ConfigService")
@XmlSeeAlso({ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface ConfigService {

    @WebMethod(operationName = "GetChildren", action = "urn:LesConfig.service.livelink.opentext.com/GetChildren")
    @Action(input = "urn:LesConfig.service.livelink.opentext.com/GetChildren", output = "urn:LesConfig.service.livelink.opentext.com/ConfigService/GetChildrenResponse")
    @RequestWrapper(localName = "GetChildren", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.GetChildren")
    @ResponseWrapper(localName = "GetChildrenResponse", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.GetChildrenResponse")
    @WebResult(name = "GetChildrenResult", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
    public java.lang.String getChildren(
        @WebParam(name = "XMLRequest", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
        java.lang.String xmlRequest
    );

    @WebMethod(operationName = "Set", action = "urn:LesConfig.service.livelink.opentext.com/Set")
    @Action(input = "urn:LesConfig.service.livelink.opentext.com/Set", output = "urn:LesConfig.service.livelink.opentext.com/ConfigService/SetResponse")
    @RequestWrapper(localName = "Set", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.Set")
    @ResponseWrapper(localName = "SetResponse", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.SetResponse")
    @WebResult(name = "SetResult", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
    public java.lang.String set(
        @WebParam(name = "XMLRequest", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
        java.lang.String xmlRequest
    );

    @WebMethod(operationName = "Get", action = "urn:LesConfig.service.livelink.opentext.com/Get")
    @Action(input = "urn:LesConfig.service.livelink.opentext.com/Get", output = "urn:LesConfig.service.livelink.opentext.com/ConfigService/GetResponse")
    @RequestWrapper(localName = "Get", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.Get")
    @ResponseWrapper(localName = "GetResponse", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.GetResponse")
    @WebResult(name = "GetResult", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
    public java.lang.String get(
        @WebParam(name = "XMLRequest", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
        java.lang.String xmlRequest
    );

    @WebMethod(operationName = "GetHelp", action = "urn:LesConfig.service.livelink.opentext.com/GetHelp")
    @Action(input = "urn:LesConfig.service.livelink.opentext.com/GetHelp", output = "urn:LesConfig.service.livelink.opentext.com/ConfigService/GetHelpResponse")
    @RequestWrapper(localName = "GetHelp", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.GetHelp")
    @ResponseWrapper(localName = "GetHelpResponse", targetNamespace = "urn:LesConfig.service.livelink.opentext.com", className = "com.opentext.livelink.service.lesconfig.GetHelpResponse")
    @WebResult(name = "GetHelpResult", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
    public java.lang.String getHelp(
        @WebParam(name = "XMLRequest", targetNamespace = "urn:LesConfig.service.livelink.opentext.com")
        java.lang.String xmlRequest
    );
}
