package com.opentext.livelink.service.docman;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:09:19.017-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "DocumentManagement", 
                  wsdlLocation = "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-document-management-ws/src/main/resources/DocumentManagement.wsdl",
                  targetNamespace = "urn:DocMan.service.livelink.opentext.com") 
public class DocumentManagement_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:DocMan.service.livelink.opentext.com", "DocumentManagement");
    public final static QName BasicHttpBindingDocumentManagement = new QName("urn:DocMan.service.livelink.opentext.com", "BasicHttpBinding_DocumentManagement");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-document-management-ws/src/main/resources/DocumentManagement.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DocumentManagement_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-document-management-ws/src/main/resources/DocumentManagement.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DocumentManagement_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocumentManagement_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentManagement_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DocumentManagement_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DocumentManagement_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DocumentManagement_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns DocumentManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentManagement")
    public DocumentManagement getBasicHttpBindingDocumentManagement() {
        return super.getPort(BasicHttpBindingDocumentManagement, DocumentManagement.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentManagement
     */
    @WebEndpoint(name = "BasicHttpBinding_DocumentManagement")
    public DocumentManagement getBasicHttpBindingDocumentManagement(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingDocumentManagement, DocumentManagement.class, features);
    }

}
