package com.opentext.livelink.service.core;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:04:59.810-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:Core.service.livelink.opentext.com", name = "Authentication")
@XmlSeeAlso({ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface Authentication {

    @WebMethod(operationName = "RefreshToken", action = "urn:Core.service.livelink.opentext.com/RefreshToken")
    @Action(input = "urn:Core.service.livelink.opentext.com/RefreshToken", output = "urn:Core.service.livelink.opentext.com/Authentication/RefreshTokenResponse")
    @RequestWrapper(localName = "RefreshToken", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.RefreshToken")
    @ResponseWrapper(localName = "RefreshTokenResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.RefreshTokenResponse")
    @WebResult(name = "RefreshTokenResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String refreshToken();

    @WebMethod(operationName = "AuthenticateUserWithApplicationToken", action = "urn:Core.service.livelink.opentext.com/AuthenticateUserWithApplicationToken")
    @Action(input = "urn:Core.service.livelink.opentext.com/AuthenticateUserWithApplicationToken", output = "urn:Core.service.livelink.opentext.com/Authentication/AuthenticateUserWithApplicationTokenResponse")
    @RequestWrapper(localName = "AuthenticateUserWithApplicationToken", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.AuthenticateUserWithApplicationToken")
    @ResponseWrapper(localName = "AuthenticateUserWithApplicationTokenResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.AuthenticateUserWithApplicationTokenResponse")
    @WebResult(name = "AuthenticateUserWithApplicationTokenResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String authenticateUserWithApplicationToken(
        @WebParam(name = "userName", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String userPassword,
        @WebParam(name = "applicationToken", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String applicationToken
    );

    @WebMethod(operationName = "GetOTDSServer", action = "urn:Core.service.livelink.opentext.com/GetOTDSServer")
    @Action(input = "urn:Core.service.livelink.opentext.com/GetOTDSServer", output = "urn:Core.service.livelink.opentext.com/Authentication/GetOTDSServerResponse")
    @RequestWrapper(localName = "GetOTDSServer", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetOTDSServer")
    @ResponseWrapper(localName = "GetOTDSServerResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetOTDSServerResponse")
    @WebResult(name = "GetOTDSServerResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String getOTDSServer();

    @WebMethod(operationName = "GetSessionExpirationDate", action = "urn:Core.service.livelink.opentext.com/GetSessionExpirationDate")
    @Action(input = "urn:Core.service.livelink.opentext.com/GetSessionExpirationDate", output = "urn:Core.service.livelink.opentext.com/Authentication/GetSessionExpirationDateResponse")
    @RequestWrapper(localName = "GetSessionExpirationDate", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetSessionExpirationDate")
    @ResponseWrapper(localName = "GetSessionExpirationDateResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetSessionExpirationDateResponse")
    @WebResult(name = "GetSessionExpirationDateResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public javax.xml.datatype.XMLGregorianCalendar getSessionExpirationDate();

    @WebMethod(operationName = "AuthenticateApplication", action = "urn:Core.service.livelink.opentext.com/AuthenticateApplication")
    @Action(input = "urn:Core.service.livelink.opentext.com/AuthenticateApplication", output = "urn:Core.service.livelink.opentext.com/Authentication/AuthenticateApplicationResponse")
    @RequestWrapper(localName = "AuthenticateApplication", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.AuthenticateApplication")
    @ResponseWrapper(localName = "AuthenticateApplicationResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.AuthenticateApplicationResponse")
    @WebResult(name = "AuthenticateApplicationResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String authenticateApplication(
        @WebParam(name = "applicationID", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String applicationID,
        @WebParam(name = "password", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String password
    );

    @WebMethod(operationName = "GetOTDSResourceID", action = "urn:Core.service.livelink.opentext.com/GetOTDSResourceID")
    @Action(input = "urn:Core.service.livelink.opentext.com/GetOTDSResourceID", output = "urn:Core.service.livelink.opentext.com/Authentication/GetOTDSResourceIDResponse")
    @RequestWrapper(localName = "GetOTDSResourceID", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetOTDSResourceID")
    @ResponseWrapper(localName = "GetOTDSResourceIDResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetOTDSResourceIDResponse")
    @WebResult(name = "GetOTDSResourceIDResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String getOTDSResourceID();

    @WebMethod(operationName = "ImpersonateApplication", action = "urn:Core.service.livelink.opentext.com/ImpersonateApplication")
    @Action(input = "urn:Core.service.livelink.opentext.com/ImpersonateApplication", output = "urn:Core.service.livelink.opentext.com/Authentication/ImpersonateApplicationResponse")
    @RequestWrapper(localName = "ImpersonateApplication", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImpersonateApplication")
    @ResponseWrapper(localName = "ImpersonateApplicationResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImpersonateApplicationResponse")
    @WebResult(name = "ImpersonateApplicationResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String impersonateApplication(
        @WebParam(name = "applicationID", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String applicationID
    );

    @WebMethod(operationName = "ImpersonateUser", action = "urn:Core.service.livelink.opentext.com/ImpersonateUser")
    @Action(input = "urn:Core.service.livelink.opentext.com/ImpersonateUser", output = "urn:Core.service.livelink.opentext.com/Authentication/ImpersonateUserResponse")
    @RequestWrapper(localName = "ImpersonateUser", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImpersonateUser")
    @ResponseWrapper(localName = "ImpersonateUserResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ImpersonateUserResponse")
    @WebResult(name = "ImpersonateUserResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String impersonateUser(
        @WebParam(name = "userName", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String userName
    );

    @WebMethod(operationName = "AuthenticateUser", action = "urn:Core.service.livelink.opentext.com/AuthenticateUser")
    @Action(input = "urn:Core.service.livelink.opentext.com/AuthenticateUser", output = "urn:Core.service.livelink.opentext.com/Authentication/AuthenticateUserResponse")
    @RequestWrapper(localName = "AuthenticateUser", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.AuthenticateUser")
    @ResponseWrapper(localName = "AuthenticateUserResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.AuthenticateUserResponse")
    @WebResult(name = "AuthenticateUserResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String authenticateUser(
        @WebParam(name = "userName", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String userName,
        @WebParam(name = "userPassword", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String userPassword
    );

    @WebMethod(operationName = "CombineApplicationToken", action = "urn:Core.service.livelink.opentext.com/CombineApplicationToken")
    @Action(input = "urn:Core.service.livelink.opentext.com/CombineApplicationToken", output = "urn:Core.service.livelink.opentext.com/Authentication/CombineApplicationTokenResponse")
    @RequestWrapper(localName = "CombineApplicationToken", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.CombineApplicationToken")
    @ResponseWrapper(localName = "CombineApplicationTokenResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.CombineApplicationTokenResponse")
    @WebResult(name = "CombineApplicationTokenResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String combineApplicationToken(
        @WebParam(name = "applicationToken", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String applicationToken
    );

    @WebMethod(operationName = "ValidateUser", action = "urn:Core.service.livelink.opentext.com/ValidateUser")
    @Action(input = "urn:Core.service.livelink.opentext.com/ValidateUser", output = "urn:Core.service.livelink.opentext.com/Authentication/ValidateUserResponse")
    @RequestWrapper(localName = "ValidateUser", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ValidateUser")
    @ResponseWrapper(localName = "ValidateUserResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.ValidateUserResponse")
    @WebResult(name = "ValidateUserResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.lang.String validateUser(
        @WebParam(name = "capToken", targetNamespace = "urn:Core.service.livelink.opentext.com")
        java.lang.String capToken
    );
}
