package com.opentext.livelink.service.core;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:04:56.644-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebService(targetNamespace = "urn:Core.service.livelink.opentext.com", name = "AdminService")
@XmlSeeAlso({ObjectFactory.class, com.opentext.ecm.api.ObjectFactory.class})
public interface AdminService {

    @WebMethod(operationName = "GetServerInfo", action = "urn:Core.service.livelink.opentext.com/GetServerInfo")
    @Action(input = "urn:Core.service.livelink.opentext.com/GetServerInfo", output = "urn:Core.service.livelink.opentext.com/AdminService/GetServerInfoResponse")
    @RequestWrapper(localName = "GetServerInfo", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetServerInfo")
    @ResponseWrapper(localName = "GetServerInfoResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetServerInfoResponse")
    @WebResult(name = "GetServerInfoResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public com.opentext.livelink.service.core.ServerInfo getServerInfo();

    @WebMethod(operationName = "GetServiceList", action = "urn:Core.service.livelink.opentext.com/GetServiceList")
    @Action(input = "urn:Core.service.livelink.opentext.com/GetServiceList", output = "urn:Core.service.livelink.opentext.com/AdminService/GetServiceListResponse")
    @RequestWrapper(localName = "GetServiceList", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetServiceList")
    @ResponseWrapper(localName = "GetServiceListResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetServiceListResponse")
    @WebResult(name = "GetServiceListResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.core.ServiceInfo> getServiceList();

    @WebMethod(operationName = "GetDateFormats", action = "urn:Core.service.livelink.opentext.com/GetDateFormats")
    @Action(input = "urn:Core.service.livelink.opentext.com/GetDateFormats", output = "urn:Core.service.livelink.opentext.com/AdminService/GetDateFormatsResponse")
    @RequestWrapper(localName = "GetDateFormats", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetDateFormats")
    @ResponseWrapper(localName = "GetDateFormatsResponse", targetNamespace = "urn:Core.service.livelink.opentext.com", className = "com.opentext.livelink.service.core.GetDateFormatsResponse")
    @WebResult(name = "GetDateFormatsResult", targetNamespace = "urn:Core.service.livelink.opentext.com")
    public java.util.List<com.opentext.livelink.service.core.DateFormat> getDateFormats();
}
