package com.opentext.livelink.service.memberservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.2
 * 2015-08-13T14:09:42.432-07:00
 * Generated source version: 3.1.2
 * 
 */
@WebServiceClient(name = "MemberService", 
                  wsdlLocation = "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-member-service-ws/src/main/resources/MemberService.wsdl",
                  targetNamespace = "urn:MemberService.service.livelink.opentext.com") 
public class MemberService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:MemberService.service.livelink.opentext.com", "MemberService");
    public final static QName BasicHttpBindingMemberService = new QName("urn:MemberService.service.livelink.opentext.com", "BasicHttpBinding_MemberService");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-member-service-ws/src/main/resources/MemberService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MemberService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/rhyse/Desktop/Content%20Server%20For%20AW16/code/contentServer.webServices/cs-member-service-ws/src/main/resources/MemberService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MemberService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MemberService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MemberService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public MemberService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public MemberService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public MemberService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns MemberService
     */
    @WebEndpoint(name = "BasicHttpBinding_MemberService")
    public MemberService getBasicHttpBindingMemberService() {
        return super.getPort(BasicHttpBindingMemberService, MemberService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MemberService
     */
    @WebEndpoint(name = "BasicHttpBinding_MemberService")
    public MemberService getBasicHttpBindingMemberService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingMemberService, MemberService.class, features);
    }

}
